name: Test

on:
  workflow_call:
    inputs:
      should-deploy:
        type: boolean
        default: true

jobs:
  setup:
    runs-on: ubuntu-24.04
    name: Build
    steps:
      - name: Build
        run: echo "Build successfully"

      - name: Deploy
        if: ${{ inputs.should-deploy }}
        run: echo "Deployed successfully"