name: Validation

on:
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup deps
        run: npm install

  build-and-deploy:
    name: Build and Deploy
    uses: ./.github/workflows/test.yml
    with:
      should-deploy: true

  build-no-deploy:
    name: Build (no deploy)
    uses: ./.github/workflows/test.yml
