name: Validation

on:
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup deps
        run: npm install

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup deps
      run: npm install

    - name: Slow CI
      run: sleep 1m

    - name: Run tests
      run: npm run test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup deps
        run: npm install

      - name: Slow CI
        run: sleep 1m

      - name: Build
        run: npm run build